//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.HistoricoSalarios = new HashSet<HistoricoSalario>();
        }
    
        public int CargoID { get; set; }
        public string NombreCargo { get; set; }
        public string Abreviatura { get; set; }
    
        public virtual ICollection<HistoricoSalario> HistoricoSalarios { get; set; }
    }
}
