//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.HistoricoSalarios = new HashSet<HistoricoSalario>();
        }
    
        public int CargoID { get; set; }
        public string NombreCargo { get; set; }
        public string Abreviatura { get; set; }
    
        public virtual ICollection<HistoricoSalario> HistoricoSalarios { get; set; }
    }
}
