//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosIngreEgre
    {
        public ConceptosIngreEgre()
        {
            this.HistoricoIngresoSalidas = new HashSet<HistoricoIngresoSalida>();
        }
    
        public int ConceptoIngreEgreID { get; set; }
        public string Concepto { get; set; }
    
        public virtual ICollection<HistoricoIngresoSalida> HistoricoIngresoSalidas { get; set; }
    }
}
