//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosHijo
    {
        public long EmpleadoHijoID { get; set; }
        public Nullable<long> EmpleadoID { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNac { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
