//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.HistoricoDirecciones = new HashSet<HistoricoDireccione>();
            this.HistoricoSucursales = new HashSet<HistoricoSucursale>();
            this.HistoricoTelefonos = new HashSet<HistoricoTelefono>();
            this.HistoricoIngresoSalidas = new HashSet<HistoricoIngresoSalida>();
            this.Ausencias = new HashSet<Ausencia>();
            this.Comisiones = new HashSet<Comisione>();
            this.HistoricoHorarios = new HashSet<HistoricoHorario>();
            this.Anticipos = new HashSet<Anticipos>();
            this.HistoricoSalarios = new HashSet<HistoricoSalario>();
            this.Imagenes = new HashSet<Imagene>();
        }
    
        public long EmpleadoID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int Sexo { get; set; }
        public int NroCedula { get; set; }
        public int EstadoCivilID { get; set; }
        public int NacionalidadID { get; set; }
        public Nullable<int> NumeroIps { get; set; }
        public Nullable<int> NumeroMjt { get; set; }
        public int ProfesionID { get; set; }
        public int CantidadHijos { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual EstadoCivile EstadoCivile { get; set; }
        public virtual Nacionalidade Nacionalidade { get; set; }
        public virtual Profesione Profesione { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<HistoricoDireccione> HistoricoDirecciones { get; set; }
        public virtual ICollection<HistoricoSucursale> HistoricoSucursales { get; set; }
        public virtual ICollection<HistoricoTelefono> HistoricoTelefonos { get; set; }
        public virtual ICollection<HistoricoIngresoSalida> HistoricoIngresoSalidas { get; set; }
        public virtual ICollection<Ausencia> Ausencias { get; set; }
        public virtual ICollection<Comisione> Comisiones { get; set; }
        public virtual ICollection<HistoricoHorario> HistoricoHorarios { get; set; }
        public virtual ICollection<Anticipos> Anticipos { get; set; }
        public virtual ICollection<HistoricoSalario> HistoricoSalarios { get; set; }
        public virtual ICollection<Imagene> Imagenes { get; set; }
    }
}
