//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosHijo
    {
        public long EmpleadoHijoID { get; set; }
        public Nullable<long> EmpleadoID { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNac { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
