//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosDatosAdicionale
    {
        public long EmpleadoID { get; set; }
        public int OrigenDocumentoID { get; set; }
        public int TipoDocumentoID { get; set; }
        public string LocalidadNacimiento { get; set; }
        public string DireccionPrincipal { get; set; }
        public string DireccionCalleSecundaria { get; set; }
        public Nullable<int> NroCasa { get; set; }
        public string LocalidadRecidencial { get; set; }
        public string BarrioRecidencial { get; set; }
        public string TelefonoParticular { get; set; }
        public string TelefonoMovil { get; set; }
        public string CorreoElectronico { get; set; }
        public string TelefonoLaboral { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Nacionalidade Nacionalidade { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
    }
}
