//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Sucursales = new HashSet<Sucursale>();
        }
    
        public int EmpresaID { get; set; }
        public string NombreEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public string Ruc { get; set; }
    
        public virtual ICollection<Sucursale> Sucursales { get; set; }
    }
}
