//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Sucursales = new HashSet<Sucursale>();
        }
    
        public int EmpresaID { get; set; }
        public string NombreEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public string Ruc { get; set; }
    
        public virtual ICollection<Sucursale> Sucursales { get; set; }
    }
}
