//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCivile
    {
        public EstadoCivile()
        {
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int EstadoCivilID { get; set; }
        public string NombreEstadoCivil { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
    }
}
