//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoHorario
    {
        public long HistoricoHorarioID { get; set; }
        public long EmpleadoID { get; set; }
        public Nullable<System.DateTime> HoraEntradaManana { get; set; }
        public Nullable<System.DateTime> HoraSalidaManana { get; set; }
        public Nullable<System.DateTime> HoraEntradaTarde { get; set; }
        public Nullable<System.DateTime> HoraSalidaTarde { get; set; }
        public Nullable<System.DateTime> HoraEntradaNoche { get; set; }
        public Nullable<System.DateTime> HoraSalidaNoche { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
