//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoHorario
    {
        public long HistoricoHorarioID { get; set; }
        public long EmpleadoID { get; set; }
        public Nullable<System.DateTime> HoraEntradaMananaUTC { get; set; }
        public Nullable<System.DateTime> HoraSalidaMananaUTC { get; set; }
        public Nullable<System.DateTime> HoraEntradaTardeUTC { get; set; }
        public Nullable<System.DateTime> HoraSalidaTardeUTC { get; set; }
        public Nullable<System.DateTime> HoraEntradaNocheUTC { get; set; }
        public Nullable<System.DateTime> HoraSalidaNocheUTC { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
