//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagene
    {
        public int ImagenID { get; set; }
        public long EmpleadoID { get; set; }
        public int TipoImagenID { get; set; }
        public byte[] Imagen { get; set; }
        public string Extencion { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoImagene TipoImagene { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
