//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagene
    {
        public int ImagenID { get; set; }
        public long EmpleadoID { get; set; }
        public int TipoImagenID { get; set; }
        public byte[] Imagen { get; set; }
        public string Extencion { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoImagene TipoImagene { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
