//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionConcepto
    {
        public LiquidacionConcepto()
        {
            this.MovEmpleadosDets = new HashSet<MovEmpleadosDet>();
        }
    
        public int LiquidacionConceptoID { get; set; }
        public string NombreConcepto { get; set; }
    
        public virtual ICollection<MovEmpleadosDet> MovEmpleadosDets { get; set; }
    }
}
