//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovEmpleado
    {
        public MovEmpleado()
        {
            this.MovEmpleadosDets = new HashSet<MovEmpleadosDet>();
            this.PrestamosSimples = new HashSet<PrestamosSimple>();
        }
    
        public long MovEmpleadoID { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public string Descripcion { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual ICollection<MovEmpleadosDet> MovEmpleadosDets { get; set; }
        public virtual ICollection<PrestamosSimple> PrestamosSimples { get; set; }
    }
}
