//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovEmpleadosDet
    {
        public long MovEmpleadoDetID { get; set; }
        public long LiquidacionEmpleadoID { get; set; }
        public long EmpleadoID { get; set; }
        public bool DevCred { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime MesAplicacion { get; set; }
        public int LiquidacionConceptoID { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual LiquidacionConcepto LiquidacionConcepto { get; set; }
        public virtual MovEmpleado MovEmpleado { get; set; }
    }
}
