//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovEmpleado
    {
        public MovEmpleado()
        {
            this.MovEmpleadosDets = new HashSet<MovEmpleadosDet>();
            this.PrestamosSimples = new HashSet<PrestamosSimple>();
        }
    
        public long MovEmpleadoID { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MovEmpleadosDet> MovEmpleadosDets { get; set; }
        public virtual ICollection<PrestamosSimple> PrestamosSimples { get; set; }
    }
}
