//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamosSimple
    {
        public long PrestamoSimpleID { get; set; }
        public long EmpleadoID { get; set; }
        public System.DateTime Fecha1erVencimiento { get; set; }
        public decimal Monto { get; set; }
        public int Cuotas { get; set; }
        public string Observacion { get; set; }
        public Nullable<long> MovEmpleadoID { get; set; }
        public long UsuarioID { get; set; }
        public System.DateTime MomentoCarga { get; set; }
        public Nullable<bool> GenerarDevitoSn { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual MovEmpleado MovEmpleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
