//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesione
    {
        public Profesione()
        {
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int ProfesionID { get; set; }
        public string NombreProfesion { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
    }
}
