//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursale
    {
        public Sucursale()
        {
            this.HistoricoSucursales = new HashSet<HistoricoSucursale>();
            this.UbicacionSucUsuarios = new HashSet<UbicacionSucUsuario>();
        }
    
        public int SucursalID { get; set; }
        public int EmpresaID { get; set; }
        public string NombreSucursal { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<HistoricoSucursale> HistoricoSucursales { get; set; }
        public virtual ICollection<UbicacionSucUsuario> UbicacionSucUsuarios { get; set; }
    }
}
