//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursale
    {
        public Sucursale()
        {
            this.UbicacionSucUsuarios = new HashSet<UbicacionSucUsuario>();
            this.HistoricoSucursales = new HashSet<HistoricoSucursale>();
        }
    
        public int SucursalID { get; set; }
        public int EmpresaID { get; set; }
        public string NombreSucursal { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<UbicacionSucUsuario> UbicacionSucUsuarios { get; set; }
        public virtual ICollection<HistoricoSucursale> HistoricoSucursales { get; set; }
    }
}
