//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDocumento
    {
        public TiposDocumento()
        {
            this.EmpleadosDatosAdicionales = new HashSet<EmpleadosDatosAdicionale>();
        }
    
        public int TipoDocumentoID { get; set; }
        public string TipoDocumento { get; set; }
    
        public virtual ICollection<EmpleadosDatosAdicionale> EmpleadosDatosAdicionales { get; set; }
    }
}
