//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoImagene
    {
        public TipoImagene()
        {
            this.Imagenes = new HashSet<Imagene>();
        }
    
        public int TipoImagenID { get; set; }
        public string NombreTipoImagen { get; set; }
    
        public virtual ICollection<Imagene> Imagenes { get; set; }
    }
}
