//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoImagene
    {
        public TipoImagene()
        {
            this.Imagenes = new HashSet<Imagene>();
        }
    
        public int TipoImagenID { get; set; }
        public string NombreTipoImagen { get; set; }
    
        public virtual ICollection<Imagene> Imagenes { get; set; }
    }
}
