//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Empleados = new HashSet<Empleado>();
            this.HistoricoIngresoSalidas = new HashSet<HistoricoIngresoSalida>();
            this.HistoricoSalarios = new HashSet<HistoricoSalario>();
            this.HistoricoTelefonos = new HashSet<HistoricoTelefono>();
            this.HistoricoDirecciones = new HashSet<HistoricoDireccione>();
        }
    
        public long UsuarioID { get; set; }
        public string NombreUsuario { get; set; }
        public System.Guid UserID { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<HistoricoIngresoSalida> HistoricoIngresoSalidas { get; set; }
        public virtual ICollection<HistoricoSalario> HistoricoSalarios { get; set; }
        public virtual ICollection<HistoricoTelefono> HistoricoTelefonos { get; set; }
        public virtual UbicacionSucUsuario UbicacionSucUsuario { get; set; }
        public virtual ICollection<HistoricoDireccione> HistoricoDirecciones { get; set; }
    }
}
