//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.HistoricoDirecciones = new HashSet<HistoricoDireccione>();
            this.Empleados = new HashSet<Empleado>();
            this.HistoricoSucursales = new HashSet<HistoricoSucursale>();
            this.HistoricoTelefonos = new HashSet<HistoricoTelefono>();
            this.HistoricoIngresoSalidas = new HashSet<HistoricoIngresoSalida>();
            this.Ausencias = new HashSet<Ausencia>();
            this.Comisiones = new HashSet<Comisione>();
            this.HistoricoHorarios = new HashSet<HistoricoHorario>();
            this.Anticipos = new HashSet<Anticipos>();
            this.HistoricoSalarios = new HashSet<HistoricoSalario>();
            this.Imagenes = new HashSet<Imagene>();
            this.PrestamosSimples = new HashSet<PrestamosSimple>();
        }
    
        public long UsuarioID { get; set; }
        public string NombreUsuario { get; set; }
        public System.Guid UserID { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual UbicacionSucUsuario UbicacionSucUsuario { get; set; }
        public virtual ICollection<HistoricoDireccione> HistoricoDirecciones { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<HistoricoSucursale> HistoricoSucursales { get; set; }
        public virtual ICollection<HistoricoTelefono> HistoricoTelefonos { get; set; }
        public virtual ICollection<HistoricoIngresoSalida> HistoricoIngresoSalidas { get; set; }
        public virtual ICollection<Ausencia> Ausencias { get; set; }
        public virtual ICollection<Comisione> Comisiones { get; set; }
        public virtual ICollection<HistoricoHorario> HistoricoHorarios { get; set; }
        public virtual ICollection<Anticipos> Anticipos { get; set; }
        public virtual ICollection<HistoricoSalario> HistoricoSalarios { get; set; }
        public virtual ICollection<Imagene> Imagenes { get; set; }
        public virtual ICollection<PrestamosSimple> PrestamosSimples { get; set; }
    }
}
